# --- Google Cloud Platform API Keys ---
GCP_API_KEY = "AIzaSyA54uQUvVuw15rQrlCpWvEGvJVWtI0D3Vw"
GOOGLE_PLACES_API_KEY = "AIzaSyA54uQUvVuw15rQrlCpWvEGvJVWtI0D3Vw"
GOOGLE_CLOUD_PLATFORM_API_KEY = "AIzaSyA54uQUvVuw15rQrlCpWvEGvJVWtI0D3Vw"
GOOGLE_PROGRAMMABLE_SEARCH_CX = "51836a88416e14eeb"
PLACES_API_KEY = "AIzaSyA54uQUvVuw15rQrlCpWvEGvJVWtI0D3Vw"

# --- Third-Party API Keys ---
HUNTER_KEY = "YOUR_HUNTER_IO_API_KEY"
HUNTER_IO_API_KEY = "REPLACE_WITH_YOUR_HUNTER_IO_API_KEY"

# --- Local Services Configuration ---
OLLAMA_BASE_URL = "http://localhost:11434"
